# Generated by Django 3.0.6 on 2020-06-02 17:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('covidapp', '0002_auto_20200602_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='suggestion',
            field=models.CharField(blank='true', default='', max_length=400, null='true', verbose_name='Suggestions/Comments(if any)_'),
        ),
    ]
