# Generated by Django 3.0.6 on 2020-06-02 18:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidapp', '0004_auto_20200602_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='rating',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='suggestion',
            field=models.CharField(blank='true', default='', max_length=400, null='true', verbose_name='Suggestions/Comments(if any)'),
        ),
    ]
