# Generated by Django 3.0.6 on 2020-06-02 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidapp', '0005_auto_20200603_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='email',
            field=models.EmailField(error_messages={'unique': 'You have already reviewed.'}, max_length=254, unique='true', verbose_name='Your Email'),
        ),
    ]
