# Generated by Django 3.0.6 on 2020-06-05 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidapp', '0006_auto_20200603_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='email',
            field=models.EmailField(error_messages={'unique': 'You have already reviewed.Thanks for the review'}, max_length=254, unique='true', verbose_name='Your Email'),
        ),
    ]
